#include <lotto/engine/pubsub.h>
#include <lotto/modules/qemu/events.h>

LOTTO_ADVERTISE_TYPE(EVENT_QEMU_INIT)
LOTTO_ADVERTISE_TYPE(EVENT_QEMU_FINI)
LOTTO_ADVERTISE_TYPE(EVENT_QEMU_START)
LOTTO_ADVERTISE_TYPE(EVENT_QEMU_STOP)
LOTTO_ADVERTISE_TYPE(EVENT_QEMU_VCPU_INIT)
LOTTO_ADVERTISE_TYPE(EVENT_QEMU_TRANSLATE)

LOTTO_MODULE_INIT()
