#include <lotto/engine/pubsub.h>
#include <lotto/modules/qemu/events.h>

FORWARD_CAPTURE_TO_INGRESS(EVENT, EVENT_QLOTTO_EXIT)
LOTTO_ADVERTISE_TYPE(EVENT_QEMU_INIT)
LOTTO_ADVERTISE_TYPE(EVENT_QEMU_FINI)
LOTTO_ADVERTISE_TYPE(EVENT_QEMU_START)
LOTTO_ADVERTISE_TYPE(EVENT_QEMU_STOP)
LOTTO_ADVERTISE_TYPE(EVENT_QEMU_VCPU_INIT)
LOTTO_ADVERTISE_TYPE(EVENT_QEMU_TRANSLATE)

LOTTO_MODULE_INIT()
