#include <lotto/engine/pubsub.h>
#include <lotto/modules/termination/events.h>

LOTTO_ADVERTISE_TYPE(EVENT_TERMINATE_SUCCESS)
LOTTO_ADVERTISE_TYPE(EVENT_TERMINATE_FAIL)
LOTTO_ADVERTISE_TYPE(EVENT_TERMINATE_STOP)

LOTTO_MODULE_INIT()
