#!/bin/sh
# Mock lotto driver for stress command
set -eu

DIR=$(readlink -f $(dirname "$0"))

if [ $# -lt 1 ]; then
    echo "[lotto-stress] error: missing command" >&2
    exit 2
fi

target=""
flags=""
target_args=""

while [ $# -gt 0 ]; do
    case "$1" in
        --)
            shift
            if [ $# -gt 0 ]; then
                target="$1"
                shift
                if [ $# -gt 0 ]; then
                    target_args="$*"
                fi
            fi
            break
            ;;
        *)
	    # ignore anything before --
            shift
            ;;
    esac
done

echo "[lotto-stress] ${target}"
count=10
for i in $(seq 1 10); do
	$DIR/lotto-run -- ${target}
done
