#include <lotto/engine/pubsub.h>
#include <lotto/modules/yield/events.h>

LOTTO_ADVERTISE_TYPE(EVENT_YIELD_SCHED)
LOTTO_ADVERTISE_TYPE(EVENT_YIELD_LOTTO)
LOTTO_ADVERTISE_TYPE(EVENT_YIELD_USER)
LOTTO_MODULE_INIT()
