#include <lotto/engine/pubsub.h>
#include <lotto/modules/deadlock/events.h>

LOTTO_ADVERTISE_TYPE(EVENT_DEADLOCK_RSRC_ACQUIRING)
LOTTO_ADVERTISE_TYPE(EVENT_DEADLOCK_RSRC_RELEASED)
LOTTO_ADVERTISE_TYPE(EVENT_DEADLOCK_DETECTED)

LOTTO_MODULE_INIT()
