#ifndef LOTTO_CORE_DRIVER_EVENTS_H
#define LOTTO_CORE_DRIVER_EVENTS_H

#define EVENT_DRIVER__MEMMGR_INIT     133
#define EVENT_DRIVER__REGISTER_FLAGS  134
#define EVENT_DRIVER__REGISTER_COMMANDS 135

#endif
