#ifndef LOTTO_CORE_ENGINE_EVENTS_H
#define LOTTO_CORE_ENGINE_EVENTS_H

#define EVENT_ENGINE__INIT                       109
#define EVENT_ENGINE__START                      110
#define EVENT_ENGINE__REPLAY_END                 111
#define EVENT_ENGINE__BEFORE_CAPTURE             112
#define EVENT_ENGINE__BEFORE_MARSHAL_CONFIG      113
#define EVENT_ENGINE__BEFORE_MARSHAL_FINAL       114
#define EVENT_ENGINE__BEFORE_MARSHAL_PERSISTENT  115
#define EVENT_ENGINE__AFTER_UNMARSHAL_CONFIG     116
#define EVENT_ENGINE__AFTER_UNMARSHAL_FINAL      117
#define EVENT_ENGINE__AFTER_UNMARSHAL_PERSISTENT 118
#define EVENT_ENGINE__INFO_RECORD_LOAD           119
#define EVENT_ENGINE__INFO_RECORD_SAVE           120
#define EVENT_ENGINE__DELAYED_PATH               121
#define EVENT_ENGINE__NEXT_TASK                  122
#define EVENT_ENGINE__REGISTER_STATE_EPHEMERAL   123
#define EVENT_ENGINE__REGISTER_STATE_START       124
#define EVENT_ENGINE__REGISTER_STATE_CONFIG      125
#define EVENT_ENGINE__REGISTER_STATE_PERSISTENT  126
#define EVENT_ENGINE__REGISTER_STATE_FINAL       127
#define EVENT_ENGINE__REGISTER_STATE_EMPTY       128

#endif
