#include <lotto/engine/pubsub.h>
#include <lotto/modules/terminate/events.h>

LOTTO_ADVERTISE_TYPE(EVENT_TERMINATE_SUCCESS)
LOTTO_ADVERTISE_TYPE(EVENT_TERMINATE_FAILURE)
LOTTO_ADVERTISE_TYPE(EVENT_TERMINATE_ABANDON)

LOTTO_MODULE_INIT()
