#!/bin/sh
# Prints a kaniko configuration. Uses environment variables provided by Gitlab CI to set
# authentication information. Code mostly taken from:
# https://docs.gitlab.com/ee/ci/docker/using_kaniko.html

KANIKOCFG="\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}"
# shellcheck disable=SC2154
if [ "x${http_proxy}" != "x" ] || [ "x${https_proxy}" != "x" ]; then
  KANIKOCFG="${KANIKOCFG}, \"proxies\": { \"default\": { \"httpProxy\": \"${http_proxy}\", \"httpsProxy\": \"${https_proxy}\", \"noProxy\": \"${no_proxy}\"}}"
fi
KANIKOCFG="{ ${KANIKOCFG} }"
echo "${KANIKOCFG}"
