#include <lotto/engine/events.h>
#include <lotto/engine/pubsub.h>
#include <lotto/util/once.h>

PS_ADVERTISE_CHAIN(CHAIN_LOTTO_CONTROL)
PS_ADVERTISE_CHAIN(CHAIN_LOTTO_DEFAULT)
PS_ADVERTISE_CHAIN(CHAIN_INGRESS_EVENT)
PS_ADVERTISE_CHAIN(CHAIN_INGRESS_AFTER)
PS_ADVERTISE_CHAIN(CHAIN_INGRESS_BEFORE)
PS_ADVERTISE_CHAIN(CHAIN_SEQUENCER_CAPTURE)
PS_ADVERTISE_CHAIN(CHAIN_SEQUENCER_RESUME)
LOTTO_ADVERTISE_TYPE(EVENT_LOTTO_REGISTER)
LOTTO_ADVERTISE_TYPE(EVENT_LOTTO_INIT)
LOTTO_ADVERTISE_TYPE(EVENT_MA_READ)
LOTTO_ADVERTISE_TYPE(EVENT_MA_WRITE)
LOTTO_ADVERTISE_TYPE(EVENT_MA_AREAD)
LOTTO_ADVERTISE_TYPE(EVENT_MA_AWRITE)
LOTTO_ADVERTISE_TYPE(EVENT_MA_RMW)
LOTTO_ADVERTISE_TYPE(EVENT_MA_XCHG)
LOTTO_ADVERTISE_TYPE(EVENT_MA_CMPXCHG)
LOTTO_ADVERTISE_TYPE(EVENT_MA_CMPXCHG_WEAK)
LOTTO_ADVERTISE_TYPE(EVENT_MA_FENCE)
LOTTO_ADVERTISE_TYPE(EVENT_MA_READ_RANGE)
LOTTO_ADVERTISE_TYPE(EVENT_MA_WRITE_RANGE)

LOTTO_MODULE_INIT()

PS_SUBSCRIBE(CHAIN_CONTROL, EVENT_DICE_READY, {
    once({
        START_REGISTRATION_PHASE();
        START_INITIALIZATION_PHASE();
    });
})
