/**
 * @file lotto_udf.h
 * @brief QEMU guest declarations for lotto udf.
 */
#ifndef LOTTO_UDF_H
#define LOTTO_UDF_H

#include <lotto/modules/qemu_profile/events.h>
#include <lotto/qemu/lotto_trap_events.h>
#include <lotto/qemu/lotto_udf_aarch64.h>

#define UDF_MASK                  AARCH64_UDF_MASK
#define LOTTO_TRAP_A64_VAL        UDF_AARCH64_INSTR_LOTTO_TRAP_VAL
#define LOTTO_TRAP_A64(op)        UDF_AARCH64_INSTR_LOTTO_TRAP(op)
#define LOTTO_TRAP1_A64(op, arg0) UDF_AARCH64_INSTR_LOTTO_TRAP1(op, arg0)
#define LOTTO_TRAP2_A64(op, arg0, arg1)                                        \
    UDF_AARCH64_INSTR_LOTTO_TRAP2(op, arg0, arg1)

// QEMU plugin specific

#define LOTTO_EXIT_SNAPSHOT_A64     UDF_AARCH64_INSTR_EXIT_SNAPSHOT
#define LOTTO_EXIT_SNAPSHOT_A64_VAL UDF_AARCH64_INSTR_EXIT_SNAPSHOT_VAL

#define LOTTO_EXIT_SUCCESS     LOTTO_TRAP_A64(EVENT_TERMINATE_SUCCESS)
#define LOTTO_EXIT_SUCCESS_VAL LOTTO_TRAP_A64_VAL

#define LOTTO_EXIT_FAILURE     LOTTO_TRAP_A64(EVENT_TERMINATE_FAILURE)
#define LOTTO_EXIT_FAILURE_VAL LOTTO_TRAP_A64_VAL

#define LOTTO_EXIT_ABANDON     LOTTO_TRAP_A64(EVENT_TERMINATE_ABANDON)
#define LOTTO_EXIT_ABANDON_VAL LOTTO_TRAP_A64_VAL

#define LOTTO_QEMU_INSTRUMENT_A64(enabled)                                     \
    LOTTO_TRAP1_A64(EVENT_QEMU_INSTRUMENT, enabled)
#define LOTTO_QEMU_INSTRUMENT_A64_VAL LOTTO_TRAP_A64_VAL


// Annotation of guest locks

#define LOTTO_LOCK_ACQ_A64(addr)                                               \
    LOTTO_TRAP1_A64(EVENT_DEADLOCK_RSRC_ACQUIRING, addr)
#define LOTTO_LOCK_ACQ_A64_VAL LOTTO_TRAP_A64_VAL

#define LOTTO_LOCK_REL_A64(addr)                                               \
    LOTTO_TRAP1_A64(EVENT_DEADLOCK_RSRC_RELEASED, addr)
#define LOTTO_LOCK_REL_A64_VAL LOTTO_TRAP_A64_VAL

#define LOTTO_LOCK_TRYACQ_SUCC_A64(addr)                                       \
    LOTTO_TRAP2_A64(EVENT_MUTEX_TRYACQUIRE, addr, 0)
#define LOTTO_LOCK_TRYACQ_SUCC_A64_VAL LOTTO_TRAP_A64_VAL

#define LOTTO_LOCK_TRYACQ_FAIL_A64(addr)                                       \
    LOTTO_TRAP2_A64(EVENT_MUTEX_TRYACQUIRE, addr, 1)
#define LOTTO_LOCK_TRYACQ_FAIL_A64_VAL LOTTO_TRAP_A64_VAL


// Lotto specific

#define LOTTO_YIELD_A64     LOTTO_TRAP_A64(EVENT_YIELD_USER)
#define LOTTO_YIELD_A64_VAL LOTTO_TRAP_A64_VAL

#define LOTTO_REGION_IN     LOTTO_TRAP_A64(EVENT_REGION_IN)
#define LOTTO_REGION_IN_VAL LOTTO_TRAP_A64_VAL

#define LOTTO_REGION_OUT     LOTTO_TRAP_A64(EVENT_REGION_OUT)
#define LOTTO_REGION_OUT_VAL LOTTO_TRAP_A64_VAL

#define LOTTO_BIAS_POLICY_A64(policy) LOTTO_TRAP1_A64(EVENT_BIAS_POLICY, policy)
#define LOTTO_BIAS_POLICY_A64_VAL     LOTTO_TRAP_A64_VAL

#define LOTTO_BIAS_TOGGLE_A64     LOTTO_TRAP_A64(EVENT_BIAS_TOGGLE)
#define LOTTO_BIAS_TOGGLE_A64_VAL LOTTO_TRAP_A64_VAL


// Start and end of profile points

#define LOTTO_PROFILE_START(id) LOTTO_TRAP1_A64(EVENT_QEMU_PROFILE_START, id)
#define LOTTO_PROFILE_START_VAL LOTTO_TRAP_A64_VAL

#define LOTTO_PROFILE_END(id) LOTTO_TRAP1_A64(EVENT_QEMU_PROFILE_END, id)
#define LOTTO_PROFILE_END_VAL LOTTO_TRAP_A64_VAL

#endif // LOTTO_UDF_H
