#include <lotto/driver/flagmgr.h>
#include <lotto/sys/assert.h>

DECLARE_FLAG_INPUT;
DECLARE_FLAG_OUTPUT;
DECLARE_FLAG_ROUNDS;
DECLARE_FLAG_VERBOSE;
DECLARE_FLAG_REPLAY_GOAL;
DECLARE_FLAG_TEMPORARY_DIRECTORY;
DECLARE_FLAG_NO_PRELOAD;
DECLARE_FLAG_LOGGER_BLOCK;
DECLARE_FLAG_BEFORE_RUN;
DECLARE_FLAG_AFTER_RUN;
DECLARE_FLAG_LOGGER_FILE;

FLAG_GETTER(input, INPUT)
FLAG_GETTER(output, OUTPUT)
FLAG_GETTER(rounds, ROUNDS)
FLAG_GETTER(verbose, VERBOSE)
FLAG_GETTER(replay_goal, REPLAY_GOAL)
FLAG_GETTER(temporary_directory, TEMPORARY_DIRECTORY)
FLAG_GETTER(no_preload, NO_PRELOAD)
FLAG_GETTER(logger_block, LOGGER_BLOCK)
FLAG_GETTER(before_run, BEFORE_RUN)
FLAG_GETTER(after_run, AFTER_RUN)
FLAG_GETTER(logger_file, LOGGER_FILE)
