#include <lotto/core/module.h>
#include <lotto/engine/pubsub.h>

PS_ADVERTISE_CHAIN(CHAIN_LOTTO_CONTROL)
PS_ADVERTISE_CHAIN(CHAIN_LOTTO_DEFAULT)
LOTTO_ADVERTISE_TYPE(EVENT_LOTTO_REGISTER)
LOTTO_ADVERTISE_TYPE(EVENT_DRIVER__REGISTER_FLAGS)
LOTTO_ADVERTISE_TYPE(EVENT_DRIVER__REGISTER_COMMANDS)
LOTTO_ADVERTISE_TYPE(EVENT_LOTTO_INIT)
LOTTO_MODULE_INIT({
    START_REGISTRATION_PHASE();
    LOTTO_PUBLISH_CONTROL(EVENT_DRIVER__REGISTER_FLAGS);
    LOTTO_PUBLISH_CONTROL(EVENT_DRIVER__REGISTER_COMMANDS);
    START_INITIALIZATION_PHASE();
})
