// WARNING: file autogenerated with mockoto 0.2-1-gc1169cb. Changes will be lost.
#include "foo.h"

#define weak_mock __attribute__((weak))

// function: foo_1
typedef int32_t (*mockoto_foo_1_f) (int32_t, uint64_t, unsigned int);
static mockoto_foo_1_f _foo_1_hook;
void mockoto_foo_1_hook(mockoto_foo_1_f cb)
{
	_foo_1_hook = cb;
}
static int32_t _foo_1_retval;
void mockoto_foo_1_returns(int32_t ret)
{
	_foo_1_retval = ret;
}
static int _foo_1_count;
int mockoto_foo_1_called(void)
{
	int count = _foo_1_count;
	_foo_1_count = 0;
	return count;
}
weak_mock int32_t
foo_1(int32_t __param_0, uint64_t __param_1, unsigned int __param_2)
{
	_foo_1_count++;
	if(_foo_1_hook)
		return _foo_1_hook(__param_0,__param_1,__param_2);
	return _foo_1_retval;
}

// function: foo_2
typedef uintptr_t (*mockoto_foo_2_f) (void *, size_t, int *);
static mockoto_foo_2_f _foo_2_hook;
void mockoto_foo_2_hook(mockoto_foo_2_f cb)
{
	_foo_2_hook = cb;
}
static uintptr_t _foo_2_retval;
void mockoto_foo_2_returns(uintptr_t ret)
{
	_foo_2_retval = ret;
}
static int _foo_2_count;
int mockoto_foo_2_called(void)
{
	int count = _foo_2_count;
	_foo_2_count = 0;
	return count;
}
weak_mock uintptr_t
foo_2(void * __param_0, size_t __param_1, int * __param_2)
{
	_foo_2_count++;
	if(_foo_2_hook)
		return _foo_2_hook(__param_0,__param_1,__param_2);
	return _foo_2_retval;
}

// function: foo_3
typedef void * (*mockoto_foo_3_f) (const char *, unsigned int *, intptr_t);
static mockoto_foo_3_f _foo_3_hook;
void mockoto_foo_3_hook(mockoto_foo_3_f cb)
{
	_foo_3_hook = cb;
}
static void * _foo_3_retval;
void mockoto_foo_3_returns(void * ret)
{
	_foo_3_retval = ret;
}
static int _foo_3_count;
int mockoto_foo_3_called(void)
{
	int count = _foo_3_count;
	_foo_3_count = 0;
	return count;
}
weak_mock void *
foo_3(const char * __param_0, unsigned int * __param_1, intptr_t __param_2)
{
	_foo_3_count++;
	if(_foo_3_hook)
		return _foo_3_hook(__param_0,__param_1,__param_2);
	return _foo_3_retval;
}

// function: foo_4
typedef uint64_t (*mockoto_foo_4_f) (uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t);
static mockoto_foo_4_f _foo_4_hook;
void mockoto_foo_4_hook(mockoto_foo_4_f cb)
{
	_foo_4_hook = cb;
}
static uint64_t _foo_4_retval;
void mockoto_foo_4_returns(uint64_t ret)
{
	_foo_4_retval = ret;
}
static int _foo_4_count;
int mockoto_foo_4_called(void)
{
	int count = _foo_4_count;
	_foo_4_count = 0;
	return count;
}
weak_mock uint64_t
foo_4(uint64_t __param_0, uint64_t __param_1, uint64_t __param_2, uint64_t __param_3, uint64_t __param_4, uint64_t __param_5)
{
	_foo_4_count++;
	if(_foo_4_hook)
		return _foo_4_hook(__param_0,__param_1,__param_2,__param_3,__param_4,__param_5);
	return _foo_4_retval;
}

// function: foo_5
typedef uint64_t (*mockoto_foo_5_f) (uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t);
static mockoto_foo_5_f _foo_5_hook;
void mockoto_foo_5_hook(mockoto_foo_5_f cb)
{
	_foo_5_hook = cb;
}
static uint64_t _foo_5_retval;
void mockoto_foo_5_returns(uint64_t ret)
{
	_foo_5_retval = ret;
}
static int _foo_5_count;
int mockoto_foo_5_called(void)
{
	int count = _foo_5_count;
	_foo_5_count = 0;
	return count;
}
weak_mock uint64_t
foo_5(uint64_t __param_0, uint64_t __param_1, uint64_t __param_2, uint64_t __param_3, uint64_t __param_4, uint64_t __param_5, uint64_t __param_6, uint64_t __param_7)
{
	_foo_5_count++;
	if(_foo_5_hook)
		return _foo_5_hook(__param_0,__param_1,__param_2,__param_3,__param_4,__param_5,__param_6,__param_7);
	return _foo_5_retval;
}

// function: foo_6
typedef struct foo_pair (*mockoto_foo_6_f) (struct foo_pair, uintptr_t);
static mockoto_foo_6_f _foo_6_hook;
void mockoto_foo_6_hook(mockoto_foo_6_f cb)
{
	_foo_6_hook = cb;
}
static struct foo_pair _foo_6_retval;
void mockoto_foo_6_returns(struct foo_pair ret)
{
	_foo_6_retval = ret;
}
static int _foo_6_count;
int mockoto_foo_6_called(void)
{
	int count = _foo_6_count;
	_foo_6_count = 0;
	return count;
}
weak_mock struct foo_pair
foo_6(struct foo_pair __param_0, uintptr_t __param_1)
{
	_foo_6_count++;
	if(_foo_6_hook)
		return _foo_6_hook(__param_0,__param_1);
	return _foo_6_retval;
}

// function: foo_7
typedef struct foo_big (*mockoto_foo_7_f) (struct foo_big, uintptr_t);
static mockoto_foo_7_f _foo_7_hook;
void mockoto_foo_7_hook(mockoto_foo_7_f cb)
{
	_foo_7_hook = cb;
}
static struct foo_big _foo_7_retval;
void mockoto_foo_7_returns(struct foo_big ret)
{
	_foo_7_retval = ret;
}
static int _foo_7_count;
int mockoto_foo_7_called(void)
{
	int count = _foo_7_count;
	_foo_7_count = 0;
	return count;
}
weak_mock struct foo_big
foo_7(struct foo_big __param_0, uintptr_t __param_1)
{
	_foo_7_count++;
	if(_foo_7_hook)
		return _foo_7_hook(__param_0,__param_1);
	return _foo_7_retval;
}

// function: foo_8
typedef double (*mockoto_foo_8_f) (double, double, float);
static mockoto_foo_8_f _foo_8_hook;
void mockoto_foo_8_hook(mockoto_foo_8_f cb)
{
	_foo_8_hook = cb;
}
static double _foo_8_retval;
void mockoto_foo_8_returns(double ret)
{
	_foo_8_retval = ret;
}
static int _foo_8_count;
int mockoto_foo_8_called(void)
{
	int count = _foo_8_count;
	_foo_8_count = 0;
	return count;
}
weak_mock double
foo_8(double __param_0, double __param_1, float __param_2)
{
	_foo_8_count++;
	if(_foo_8_hook)
		return _foo_8_hook(__param_0,__param_1,__param_2);
	return _foo_8_retval;
}

// function: foo_9
typedef uint64_t (*mockoto_foo_9_f) (uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t);
static mockoto_foo_9_f _foo_9_hook;
void mockoto_foo_9_hook(mockoto_foo_9_f cb)
{
	_foo_9_hook = cb;
}
static uint64_t _foo_9_retval;
void mockoto_foo_9_returns(uint64_t ret)
{
	_foo_9_retval = ret;
}
static int _foo_9_count;
int mockoto_foo_9_called(void)
{
	int count = _foo_9_count;
	_foo_9_count = 0;
	return count;
}
weak_mock uint64_t
foo_9(uint64_t __param_0, uint64_t __param_1, uint64_t __param_2, uint64_t __param_3, uint64_t __param_4, uint64_t __param_5, uint64_t __param_6, uint64_t __param_7, uint64_t __param_8, uint64_t __param_9, uint64_t __param_10, uint64_t __param_11)
{
	_foo_9_count++;
	if(_foo_9_hook)
		return _foo_9_hook(__param_0,__param_1,__param_2,__param_3,__param_4,__param_5,__param_6,__param_7,__param_8,__param_9,__param_10,__param_11);
	return _foo_9_retval;
}

// function: foo_10
typedef struct foo_huge (*mockoto_foo_10_f) (struct foo_huge, uintptr_t, uint32_t);
static mockoto_foo_10_f _foo_10_hook;
void mockoto_foo_10_hook(mockoto_foo_10_f cb)
{
	_foo_10_hook = cb;
}
static struct foo_huge _foo_10_retval;
void mockoto_foo_10_returns(struct foo_huge ret)
{
	_foo_10_retval = ret;
}
static int _foo_10_count;
int mockoto_foo_10_called(void)
{
	int count = _foo_10_count;
	_foo_10_count = 0;
	return count;
}
weak_mock struct foo_huge
foo_10(struct foo_huge __param_0, uintptr_t __param_1, uint32_t __param_2)
{
	_foo_10_count++;
	if(_foo_10_hook)
		return _foo_10_hook(__param_0,__param_1,__param_2);
	return _foo_10_retval;
}

// function: foo_11
typedef int64_t (*mockoto_foo_11_f) (int8_t, uint16_t, int32_t, uint64_t, intptr_t, size_t, int8_t, uint16_t, int64_t);
static mockoto_foo_11_f _foo_11_hook;
void mockoto_foo_11_hook(mockoto_foo_11_f cb)
{
	_foo_11_hook = cb;
}
static int64_t _foo_11_retval;
void mockoto_foo_11_returns(int64_t ret)
{
	_foo_11_retval = ret;
}
static int _foo_11_count;
int mockoto_foo_11_called(void)
{
	int count = _foo_11_count;
	_foo_11_count = 0;
	return count;
}
weak_mock int64_t
foo_11(int8_t __param_0, uint16_t __param_1, int32_t __param_2, uint64_t __param_3, intptr_t __param_4, size_t __param_5, int8_t __param_6, uint16_t __param_7, int64_t __param_8)
{
	_foo_11_count++;
	if(_foo_11_hook)
		return _foo_11_hook(__param_0,__param_1,__param_2,__param_3,__param_4,__param_5,__param_6,__param_7,__param_8);
	return _foo_11_retval;
}

// function: foo_12
typedef void (*mockoto_foo_12_f) (uint32_t *, uint64_t *, const void *, size_t, int);
static mockoto_foo_12_f _foo_12_hook;
void mockoto_foo_12_hook(mockoto_foo_12_f cb)
{
	_foo_12_hook = cb;
}
static int _foo_12_count;
int mockoto_foo_12_called(void)
{
	int count = _foo_12_count;
	_foo_12_count = 0;
	return count;
}
weak_mock void
foo_12(uint32_t * __param_0, uint64_t * __param_1, const void * __param_2, size_t __param_3, int __param_4)
{
	_foo_12_count++;
	if(_foo_12_hook)
		_foo_12_hook(__param_0,__param_1,__param_2,__param_3,__param_4);
}
