// WARNING: file autogenerated with mockoto 0.2-1-gc1169cb. Changes will be lost.
#ifndef MOCKOTO__H
#define MOCKOTO__H

#include "/home/diogo/Workspaces/lotto/modules/autocept/test/foo.h"

// function: foo_1
typedef int32_t (*mockoto_foo_1_f) (int32_t, uint64_t, unsigned int);
void mockoto_foo_1_hook(mockoto_foo_1_f cb);
void mockoto_foo_1_returns(int32_t ret);
int mockoto_foo_1_called(void);

// function: foo_2
typedef uintptr_t (*mockoto_foo_2_f) (void *, size_t, int *);
void mockoto_foo_2_hook(mockoto_foo_2_f cb);
void mockoto_foo_2_returns(uintptr_t ret);
int mockoto_foo_2_called(void);

// function: foo_3
typedef void * (*mockoto_foo_3_f) (const char *, unsigned int *, intptr_t);
void mockoto_foo_3_hook(mockoto_foo_3_f cb);
void mockoto_foo_3_returns(void * ret);
int mockoto_foo_3_called(void);

// function: foo_4
typedef uint64_t (*mockoto_foo_4_f) (uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t);
void mockoto_foo_4_hook(mockoto_foo_4_f cb);
void mockoto_foo_4_returns(uint64_t ret);
int mockoto_foo_4_called(void);

// function: foo_5
typedef uint64_t (*mockoto_foo_5_f) (uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t);
void mockoto_foo_5_hook(mockoto_foo_5_f cb);
void mockoto_foo_5_returns(uint64_t ret);
int mockoto_foo_5_called(void);

// function: foo_6
typedef struct foo_pair (*mockoto_foo_6_f) (struct foo_pair, uintptr_t);
void mockoto_foo_6_hook(mockoto_foo_6_f cb);
void mockoto_foo_6_returns(struct foo_pair ret);
int mockoto_foo_6_called(void);

// function: foo_7
typedef struct foo_big (*mockoto_foo_7_f) (struct foo_big, uintptr_t);
void mockoto_foo_7_hook(mockoto_foo_7_f cb);
void mockoto_foo_7_returns(struct foo_big ret);
int mockoto_foo_7_called(void);

// function: foo_8
typedef double (*mockoto_foo_8_f) (double, double, float);
void mockoto_foo_8_hook(mockoto_foo_8_f cb);
void mockoto_foo_8_returns(double ret);
int mockoto_foo_8_called(void);

// function: foo_9
typedef uint64_t (*mockoto_foo_9_f) (uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t, uint64_t);
void mockoto_foo_9_hook(mockoto_foo_9_f cb);
void mockoto_foo_9_returns(uint64_t ret);
int mockoto_foo_9_called(void);

// function: foo_10
typedef struct foo_huge (*mockoto_foo_10_f) (struct foo_huge, uintptr_t, uint32_t);
void mockoto_foo_10_hook(mockoto_foo_10_f cb);
void mockoto_foo_10_returns(struct foo_huge ret);
int mockoto_foo_10_called(void);

// function: foo_11
typedef int64_t (*mockoto_foo_11_f) (int8_t, uint16_t, int32_t, uint64_t, intptr_t, size_t, int8_t, uint16_t, int64_t);
void mockoto_foo_11_hook(mockoto_foo_11_f cb);
void mockoto_foo_11_returns(int64_t ret);
int mockoto_foo_11_called(void);

// function: foo_12
typedef void (*mockoto_foo_12_f) (uint32_t *, uint64_t *, const void *, size_t, int);
void mockoto_foo_12_hook(mockoto_foo_12_f cb);
int mockoto_foo_12_called(void);

#endif
