/*
 */
#ifndef LOTTO_UDF_H
#define LOTTO_UDF_H

#include <lotto/qemu/lotto_udf_aarch64.h>
#include <lotto/qemu/lotto_udf_trace.h>

#define UDF_MASK AARCH64_UDF_MASK

// QEMU plugin specific

#define LOTTO_SNAPSHOT_A64     UDF_AARCH64_INSTR_SNAPSHOT
#define LOTTO_SNAPSHOT_A64_VAL UDF_AARCH64_INSTR_SNAPSHOT_VAL

#define LOTTO_QEMUQUIT_A64     UDF_AARCH64_INSTR_QEMUQUIT
#define LOTTO_QEMUQUIT_A64_VAL UDF_AARCH64_INSTR_QEMUQUIT_VAL

#define LOTTO_TEST_SUCCESS     UDF_AARCH64_INSTR_TEST_SUCCESS
#define LOTTO_TEST_SUCCESS_VAL UDF_AARCH64_INSTR_TEST_SUCCESS_VAL

#define LOTTO_TEST_FAIL     UDF_AARCH64_INSTR_TEST_FAIL
#define LOTTO_TEST_FAIL_VAL UDF_AARCH64_INSTR_TEST_FAIL_VAL

/* Disables plugin-lotto loop detection for current translation block */
#define LOTTO_NO_INSTRUMENT     UDF_AARCH64_INSTR_NO_INSTRUMENT
#define LOTTO_NO_INSTRUMENT_VAL UDF_AARCH64_INSTR_NO_INSTRUMENT_VAL


// Annotation of guest locks

#define LOTTO_LOCK_ACQ_A64     UDF_AARCH64_INSTR_LOCK_ACQ
#define LOTTO_LOCK_ACQ_A64_VAL UDF_AARCH64_INSTR_LOCK_ACQ_VAL

#define LOTTO_LOCK_REL_A64     UDF_AARCH64_INSTR_LOCK_REL
#define LOTTO_LOCK_REL_A64_VAL UDF_AARCH64_INSTR_LOCK_REL_VAL

#define LOTTO_LOCK_TRYACQ_A64     UDF_AARCH64_INSTR_LOCK_TRYACQ
#define LOTTO_LOCK_TRYACQ_A64_VAL UDF_AARCH64_INSTR_LOCK_TRYACQ_VAL

#define LOTTO_LOCK_TRYACQ_SUCC_A64     UDF_AARCH64_INSTR_LOCK_TRYACQ_SUCC
#define LOTTO_LOCK_TRYACQ_SUCC_A64_VAL UDF_AARCH64_INSTR_LOCK_TRYACQ_SUCC_VAL

#define LOTTO_LOCK_TRYACQ_FAIL_A64     UDF_AARCH64_INSTR_LOCK_TRYACQ_FAIL
#define LOTTO_LOCK_TRYACQ_FAIL_A64_VAL UDF_AARCH64_INSTR_LOCK_TRYACQ_FAIL_VAL


// Lotto specific

#define LOTTO_YIELD_A64     UDF_AARCH64_INSTR_YIELD
#define LOTTO_YIELD_A64_VAL UDF_AARCH64_INSTR_YIELD_VAL

#define LOTTO_REGION_IN     UDF_AARCH64_INSTR_REGION_IN
#define LOTTO_REGION_IN_VAL UDF_AARCH64_INSTR_REGION_IN_VAL

#define LOTTO_REGION_OUT     UDF_AARCH64_INSTR_REGION_OUT
#define LOTTO_REGION_OUT_VAL UDF_AARCH64_INSTR_REGION_OUT_VAL


// Start and end of trace points

#define LOTTO_TRACE_START(id) UDF_AARCH64_INSTR_TRACE_START(id)
#define LOTTO_TRACE_START_VAL UDF_AARCH64_INSTR_TRACE_START_VAL

#define LOTTO_TRACE_END(id) UDF_AARCH64_INSTR_TRACE_END(id)
#define LOTTO_TRACE_END_VAL UDF_AARCH64_INSTR_TRACE_END_VAL

#endif // LOTTO_UDF_H
