#!/bin/bash

# called as ./scripts/gen_ps_internal.sh <HEADER_INTERNAL> <INTERNAL_TOPIC1[,INTERNAL_TOPIC2[;...]]> <EXTERNAL_TOPIC1[;EXTERNAL_TOPIC2[;...]]>

HEADER_INTERNAL="${1}"
INTERNAL_TOPICS=${2}
EXTERNAL_TOPICS=${3}

if [ "x${HEADER_INTERNAL}" == "x" ];
then
    exit 0
fi

if [ -f "${HEADER_INTERNAL}" ]; then
    exit 0
fi

cat <<EOF >"${HEADER_INTERNAL}"
/*
 * Auto generated by ${0}
 */
#ifndef LOTTO_PS_INTERFACE_INTERNAL_AUTOGEN_H
#define LOTTO_PS_INTERFACE_INTERNAL_AUTOGEN_H
EOF

externals=$(echo $EXTERNAL_TOPICS | tr "," "\n")

for external in $externals
do
    echo "#define PS_SUBSCRIBE_INTERFACE_${external}(callee, topic, CALLBACK) PS_SUBSCRIBE(topic, CALLBACK)" >> "${HEADER_INTERNAL}"
    echo "#define PS_PUBLISH_INTERFACE_${external}(topic, value) ps_publish(topic, value);"  >> "${HEADER_INTERNAL}"
done

internals=$(echo $INTERNAL_TOPICS | tr "," "\n")

for internal in $internals
do
    echo "#define PS_SUBSCRIBE_INTERFACE_${internal}(callee, topic, CALLBACK) void _ps_callee_##callee##_##topic(struct value v, void *__) { (CALLBACK); }"  >> "${HEADER_INTERNAL}"
    echo "#define PS_PUBLISH_INTERFACE_${internal}(topic, val) { GEN_CALLEES(topic, val) }"  >> "${HEADER_INTERNAL}"
done

echo "#endif" >> "${HEADER_INTERNAL}"
