#!/bin/sh
set -e
ROOTDIR=$(readlink -f $(dirname "$0")/..)

if [ -z "$LOTTO_BUILD" ]; then
	LOTTO_BUILD="$ROOTDIR/build"
fi

DICE_SOURCE="$ROOTDIR/deps/dice"
DICE_BUILD="$LOTTO_BUILD/deps/dice"

LDPRELOAD=${LOTTO_BUILD}/liblotto.so
if [ ! -z "$PRELOAD" ]; then
	#LDPRELOAD="$LDPRELOAD:$PRELOAD"
	LDPRELOAD="$PRELOAD:$LDPRELOAD"
fi

exec env \
	DICE_SOURCE="$DICE_SOURCE" \
	DICE_BUILD="$DICE_BUILD" \
	${DICE_SOURCE}/scripts/dice \
	-with  "$LDPRELOAD" \
	$@
