#include <lotto/engine/pubsub.h>
#include <lotto/modules/mutex/events.h>

LOTTO_ADVERTISE_TYPE(EVENT_MUTEX_ACQUIRE)
LOTTO_ADVERTISE_TYPE(EVENT_MUTEX_TRYACQUIRE)
LOTTO_ADVERTISE_TYPE(EVENT_MUTEX_RELEASE)

LOTTO_MODULE_INIT()
