name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake
      - name: Configure
        run: cmake -S . -B build
      - name: Build and run integration tests
        run: cmake --build build --target check-integration
